
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      return knex('users').insert([
        {
          id: 1,
          first_name: 'Sam',
          last_name: 'Miller',
          email: 'sammzamm01@gmail.com ',
          hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS',
          gender: 1,
          age: 28,
          looking_for: true,
          interested_in: 2,
          bio: 'I am Sam. I created this app so that I can get a date. Want to go out with me yet?',
          usr_name: 'SammZamm',
          lat: 40.068337,
          long: -105.1820337,
          photo: '/img/SammZamm1.jpg',
          photo2: '/img/SammZamm2.jpg',
          photo3: '/img/SammZamm3.jpg',
          photo4: '/img/SammZamm4.jpg'
        },
        {
          id: 2,
          first_name: 'Haley',
          last_name: 'Kalb',
          email: 'haley.kalb@gmail.com ',
          hashed_password: '$4a$90$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS',
          gender: 2,
          age: 34,
          looking_for: false,
          interested_in: 1,
          bio: 'I am kind of a big deal.',
          usr_name: 'RucaLove',
          lat: 40.0228514,
          long: -105.2544565,
          photo: '/img/RucaLove1.jpg',
          photo2: '/img/RucaLove2.jpg',
          photo3: '/img/RucaLove3.jpg',
          photo4: '/img/RucaLove4.jpg'
        },
        {
          id: 3,
          first_name: 'Nico',
          last_name: 'Roldos',
          email: 'nico.roldos@me.com',
          hashed_password: 'EAACCAVAZCUOoBAAA097G5WMfuA2O3c2xFyk7QCfpYe9FZCpDyZCAhYRVg2YT15Q',
          gender: 1,
          age: 28,
          looking_for: true,
          interested_in: 2,
          bio: 'I drive a Subaru.',
          usr_name: 'Nicowave',
          lat: 40.0207741,
          long: -105.277141,
          photo: '/img/NicoWave1.jpg',
          photo2: '/img/NicoWave2.jpg',
          photo3: '/img/NicoWave3.jpg',
          photo4: '/img/NicoWave4.jpg'
        },
        {
          id: 4,
          first_name: 'Megan',
          last_name: 'Gross',
          email: '144.mdgross@gmail.com',
          hashed_password: 'EBBCCAVAZCUOoBAAA097G5WMfuA2O3c2xFyk7QCfpYe9FZCpDyZCAhYRVg2YT15Q',
          gender: 2,
          age: 26,
          looking_for: true,
          interested_in: 1,
          bio: 'My teammates love me endlessly.',
          usr_name: 'Gross',
          lat: 40.0207741,
          long: -105.277141,
          photo: '/img/Gross1.jpg',
          photo2: '/img/Gross2.jpg',
          photo3: '/img/Gross3.jpg',
          photo4: '/img/Gross4.jpg'
        },
        {
          id: 5,
          first_name: 'Lisa',
          last_name: 'Ma',
          email: 'limawebdev@gmail.com',
          hashed_password: 'ECCCCAVAZCUOoBAAA097G5WMfuA2O3c2xFyk7QCfpYe9FZCpDyZCAhYRVg2YT15Q',
          gender: 2,
          age: 23,
          looking_for: false,
          interested_in: 1,
          bio: 'I only date unicorns.',
          usr_name: 'ChubbyBunny',
          lat: 40.0207741,
          long: -105.277141,
          photo: '/img/Ma1.jpg',
          photo2: '/img/Ma2.jpg',
          photo3: '/img/Ma3.jpg',
          photo4: '/img/Ma4.jpg'
        },
        {
          id: 6,
          first_name: 'Craig',
          last_name: 'Quincy',
          email: 'craig.quincy@galvanize.com',
          hashed_password: 'EDDCCAVAZCUOoBAAA097G5WMfuA2O3c2xFyk7QCfpYe9FZCpDyZCAhYRVg2YT15Q',
          gender: 1,
          age: 48,
          looking_for: true,
          interested_in: 2,
          bio: 'I am the all mighty ruler of g44.',
          usr_name: 'Craag',
          lat: 40.0207741,
          long: -105.277141,
          photo: '/img/Craag1.jpg',
          photo2: '/img/Craag2.jpg',
          photo3: '/img/Craag3.jpg',
          photo4: '/img/Craag4.jpg'
        },
        {
          id: 7,
          first_name: 'Tiffany',
          last_name: 'Perfection',
          email: 'tiffany@gmail.com',
          hashed_password: 'EEEDDAVAZCUOoBAAA097G5WMfuA2O3c2xFyk7QCfpYe9FZCpDyZCAhYRVg2YT15Q',
          gender: 2,
          age: 26,
          looking_for: true,
          interested_in: 1,
          bio: 'I am your perfect match.',
          usr_name: 'Tiffany',
          lat: 40.0207741,
          long: -105.277141,
          photo: '/img/Wifey1.jpg',
          photo2: '/img/Wifey2.jpg',
          photo3: '/img/Wifey3.jpg',
          photo4: '/img/Wifey4.jpg'
        },
        {
          id: 8,
          first_name: 'Kelly',
          last_name: 'Cordes',
          email: 'kellycordes@gmail.com',
          hashed_password: 'EEEEEAVAZCUOoBAAA097G5WMfuA2O3c2xFyk7QCfpYe9FZCpDyZCAhYRVg2YT15Q',
          gender: 1,
          age: 41,
          looking_for: false,
          interested_in: 2,
          bio: 'I climb and I have the best mullet in all the land.',
          usr_name: 'MulletMan',
          lat: 40.0207741,
          long: -105.277141,
          photo: '/img/Kelly1.jpg',
          photo2: '/img/Kelly2.jpg',
          photo3: '/img/Kelly3.jpg',
          photo4: '/img/Kelly4.jpg'
        },
        {
          id: 9,
          first_name: 'Leelah',
          last_name: 'Joi',
          email: 'leelahjoi@gmail.com',
          hashed_password: 'EFFEEAVAZCUOoBAAA097G5WMfuA2O3c2xFyk7QCfpYe9FZCpDyZCAhYRVg2YT15Q',
          gender: 2,
          age: 30,
          looking_for: false,
          interested_in: 1,
          bio: 'Is my perfect match out there?',
          usr_name: 'Leelah',
          lat: 40.0207741,
          long: -105.277141,
          photo: '/img/Leelah1.jpg',
          photo2: '/img/Leelah2.jpg',
          photo3: '/img/Leelah3.jpg',
          photo4: '/img/Leelah4.jpg'
        },
        {
          id: 10,
          first_name: 'Andrew',
          last_name: 'Varnell',
          email: 'andrewvarnell@gmail.com',
          hashed_password: 'EGGEEAVAZCUOoBAAA097G5WMfuA2O3c2xFyk7QCfpYe9FZCpDyZCAhYRVg2YT15Q',
          gender: 1,
          age: 25,
          looking_for: true,
          interested_in: 2,
          bio: 'I am a Galvanize alumni. I love coding.',
          usr_name: 'Andy',
          lat: 40.0207741,
          long: -105.277141,
          photo: '/img/Andrew1.jpg',
          photo2: '/img/Andrew2.jpg',
          photo3: '/img/Andrew3.jpg',
          photo4: '/img/Andrew4.jpg'
        }
      ]);
    })
  .then(() => {
    return knex.raw("SELECT setval('users_id_seq', (SELECT MAX(id) FROM users))");
  })
};
